POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRoZS1NZW1pbiIsImlkIjoiNjg4ZDE4NDdiNWIzMjljZTY1NGY2NzY4IiwiaWF0IjoxNzU0MDc3Mjc1fQ.aihr71D0CQ3IcrzneuEEpalOAYlhDVg25zuyZgnacF4

{
  "content": "Single page apps use token authentication",
  "important": false
}